services:
  - type: web
    name: solana-trading-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: PRIVATE_KEY
        value: A8sp6y9ZGZx2A4KACZmkhcBjdVEWPG77udAuSUfcSF9A
